name: Terraform and Docker

on:
  push:
    branches:
      - main
      - dev
      - staging

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  TF_VAR_ENVIRONMENT: ${{ github.ref == 'refs/heads/dev' && 'dev' || github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/staging' && 'staging' }}
  GITHUB_REGISTRY: ghcr.io/${{ github.repository }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Select or Create Terraform Workspace
        run: |
          cd HuggingFace/aws/
          WORKSPACE_NAME=${{ github.ref == 'refs/heads/dev' && 'dev' || github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/staging' && 'staging' }}
          echo "Terraform workspace: $WORKSPACE_NAME"
          terraform workspace select $WORKSPACE_NAME || terraform workspace new $WORKSPACE_NAME

      - name: Terraform Init and Plan
        run: |
          cd HuggingFace/aws/
          terraform init && terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: |
          cd HuggingFace/aws
          terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd HuggingFace/aws
          terraform destroy -auto-approve

  build_and_tag_docker:
    runs-on: ubuntu-latest
    # needs: [terraform]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
  
      - name: Build and tag Docker image
        run: |
            cd HuggingFace/Docker/
            docker build -t ${{ secrets.DOCKER_HUB_USERNAME}}/huggingface:latest .
            docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/huggingface:latest ${{ secrets.DOCKER_HUB_USERNAME }}/mysqlrestapi:${{ github.sha }}
  
      - name: Push Docker image to Docker Hub
        run: |
            docker push ${{ secrets.DOCKER_HUB_USERNAME}}/huggingface:latest
            docker push ${{ secrets.DOCKER_HUB_USERNAME}}/huggingface:${{ github.sha }}

  push_docker:
    runs-on: ubuntu-latest
    needs: [terraform, build_and_tag_docker]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
